language: php

# PHP version to test against
php:

  # 5.2.17
  - 5.2
  # 5.3.29
  - 5.3
  # 5.4.x version
  - 5.4
  # 5.5.x version
  - 5.5
  # 5.6.x version
  - 5.6
  # recent 7.x version
  - 7.0
  
php:
  - hhvm-3.3
  - hhvm-3.6
  - hhvm-3.9
  - hhvm-3.12
  - hhvm-3.15
  - hhvm-3.18
  - hhvm-nightly

dist: trusty
sudo: required

addons:
  firefox: "50.0"

matrix:
  include:
    - php: 5.2
      dist: precise
    - php: 5.3
      dist: precise

#test environment of database
env:
  - DB=mysql 

# before script run a test 
before script: 
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS registered_users_test;" -uroot; fi
  
script: 
sudo -E su $USER -c 'COMMAND1; COMMAND2; COMMAND3'

notifications:
  slack: ${SLACK_API_KEY}
