language: php

# PHP version to test against
php:

  # 5.2.17
  - 5.2
  # 5.3.29
  - 5.3
  # 5.4.x version
  - 5.4
  # 5.5.x version
  - 5.5
  # 5.6.x version
  - 5.6
  # recent 7.x version
  - 7.0
  

#test environment of database
env:
  - DB=mysql 

# before script run a test 
before script: 
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS registered_users_test;" -uroot; fi

script: 
phpunit --configuration phpunit_$DB.xml --coverage-text

notifications:
  slack: ${SLACK_API_KEY}
